

laime: soc_course shmiga
	@echo "Shmigojam 4ever"

shmiga: nauda
	@echo "Vecriga, ala, tolete, majas"

nauda: soc_course
	@echo "Stradat"
	
soc_course:
	@echo "Pabeigt problem setus"
	@echo "Izdomat kursa darba teemu"
	