


laime: soc_course shmiga
	@echo "shmigojam 4ever"

shmiga: nauda
	@echo "Vecriga, ala, cels uz majam" 

nauda: soc_course
	@echo "Stradat"

soc_course:
	@echo "Pabeigt problem set"
	@echo "izdomat kursadarba temu"
